name: Main Infra → Code Workflow

on:
  workflow_dispatch:

jobs:
  setup-ecr:
    runs-on: ubuntu-latest
    name: Step 1 - Create ECR repos

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform & Create ECR
        run: echo "Create ECR and Trigger Repo B"
        # run: terraform apply -target=aws_ecr_repository.writer -target=aws_ecr_repository.reader -auto-approve

      - name: Trigger Docker Image Build (Repo B)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}  # Pass the token directly here
          repository: makgopajm/repB
          event-type: build-lambda-images
